### PR TITLE
Add dictionary for Russian language

### PR DESCRIPTION
**Pull request by sviperm**
I used similar dataset to create wordfreq dictionary for Russian language. Added archives in `scripts` and `resoures` folders. I tested this code, everything works fine.

```python
from spellchecker import SpellChecker

spell = SpellChecker(language='ru')

# find those words that may be misspelled
misspelled = spell.unknown('отфильтруй по убыванию отсортируй по городу'.split())

for word in misspelled:
    print(word)

    # Get a list of `likely` options
    print(spell.candidates(word))

    # Get the one `most likely` answer
    print(spell.correction(word))
```

Unfortunately, you didnt writes rules and examples for PRs, so I expect you'll do other stuff (writing tests, changing versions, etc.). Anyway fell free to ask any question!

### CODE REVIEW

**Review by barrust — APPROVED** [review]
This is great! As you are the first to add a new dictionary, how was the process? Any feedback to help with the documentation would be helpful!
Thanks!

**Comment by barrust** [comment]
Thanks! This is amazing. You are correct, I haven't gotten around to documenting what to put into a PR or testing. I will do version updates, etc. Is there anything in particular about the dictionary that should be tested?

**Comment by sviperm** [comment]
Hello there, @barrust ! Sorry for the late answer! Your code is great + every function have informative docstrings. So I wanted to change some code, but decided to ask your opinion. 

1. Every [`clean_<language>`](https://github.com/barrust/pyspellchecker/blob/777248c9845154424c4ea47d577c37d15b70f4f5/scripts/build_dictionary.py#L214) function have this lines of code:
```python
    # remove flagged misspellings
    with load_file(filepath_exclude) as fobj:
        for line in fobj:
            line = line.strip()
            if line in word_frequency:
                word_frequency.pop(line)

    # Add known missing words back in (ugh)
    with load_file(filepath_include) as fobj:
        for line in fobj:
            line = line.strip()
            if line in word_frequency:
                print("{} is already found in the dictionary! Skipping!")
            else:
                word_frequency[line] = MINIMUM_FREQUENCY
```
I think it should be moving outside to separate functions. DRY principle.

2. I wanted to change keyword args in [`_parse_args`](https://github.com/barrust/pyspellchecker/blob/777248c9845154424c4ea47d577c37d15b70f4f5/scripts/build_dictionary.py#L57) function. `-p` and `-P` have similar letter, but different cases. I suggest to change:
    -  `"-p", "--path"` -> `"-f", "--file_path"`
    - `"-P", "--parse_input"` -> `"-p", "--parse_input"`
3. Autocreation `exlude.txt` and `include.txt` if files dont exist.

Now about dataset, I thought similar test like [`test_spanish_dict`](https://github.com/barrust/pyspellchecker/blob/777248c9845154424c4ea47d577c37d15b70f4f5/tests/spellchecker_test.py#L109) for cyrilic letters will be great, but this is standart `utf-8` coding, so decide yourself.

And info about initiating different languages in readme, like code below, will be great.
```python
SpellChecker(language='ru')
SpellChecker(language='en')
# etc
```

Thank you for merging Russian dictionary, may be on this week I'll prepare even bigger dictionary. This PR is fine and I suggest to move discussion to disscussion tab, which you've created or issue tab  for readme and etc. :)

**Comment by barrust** [comment]
Thanks for the feedback! I will update the README.md with language information. As for the other ideas, go ahead and put an issue in for the args and auto create those files so that it can be tracked. 
Thanks!

**Pull request merged**
