### PR TITLE
add case sensitive option

### PR DESCRIPTION
**Pull request by davido-brainlabs**
Allows users to set whether spellchecking should be case sensitive or not.
Overrides to case insensitive when language specified.

### CODE REVIEW

**Comment by barrust** [comment]
Thank you for the PR! I am happy to accept it (it looks great) but it will likely be a few weeks until I can package and push out an updated package.

**Comment by davido-brainlabs** [comment]
@barrust do you know when it might be possible to push out an updated package?

**Comment by barrust** [comment]
It should be later this week, things are hectic at work. I will update this when it is done!

**Comment by barrust** [comment]
It has been released in [version 0.5.0](https://github.com/barrust/pyspellchecker/releases/tag/v0.5.0) and it was uploaded to pypi.

**Pull request merged**
